django_movies/accounts/urls.py
from django.urls import path

from .views import SubmittableLoginView, SubmittablePasswordChangeView, SuccessMessagedLogoutView, SignUpView

app_name = 'accounts'
urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('passchange/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('logout/', SuccessMessagedLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup')
]

django_movies/core/urls.py
from django.contrib import admin
from django.urls import path

from core.views import MovieView, MovieCreateView, MovieUpdateView, MovieDeleteView, MovieListView, MovieDetailView


app_name = 'core'
urlpatterns = [
    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete'),
]

django_movies/django_movies/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import hello
from .views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello, name='hello'),
    path('', IndexView.as_view(), name='index'),
    path('core/', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

django_movies/django_movies/views.py
from core.views import MovieListView


class IndexView(MovieListView):
    template_name = 'index.html'

django_movies/django_movies/templates/base.html
​
{% load bootstrap4 %}
{% load static %}
​
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>
​
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>
​
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
        <a class="navbar-brand" href="{% url 'index' %}">Django Movies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
            <div class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                Movies
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'core:movie_list' %}">List</a>
                <a class="dropdown-item" href="{% url 'core:movie_create' %}">Create</a>
              </div>
            </div>
          </div>
          <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
              {% if user.is_authenticated %}
                <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                  {% if user.first_name %}Hello, {{ user.first_name }}!
                  {% else %}Hello, {{ user.username }}!{% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                    <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change password</a>
                </div>
              {% else %}
                <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                  You are not logged in.
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
                  <a class="dropdown-item text-right" href="{% url 'accounts:signup' %}">Sign up</a>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
​
</html>

django_movies/django_movies/templates/form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}








{% comment %}

{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <input type="submit" value="Submit" class="btn btn-primary">
        {% endbuttons %}
    </form>
{% endblock %}

{% endcomment %}

django_movies/django_movies/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Hello, world! </title>
</head>
<body>
    <h1>Hello, my friend...</h1>
    {% for adjective in adjectives %}
        {% if adjective != 'cruel' %}
            <p>This is a {{ adjective }} world...</p>
        {% endif %}
    {% endfor %}
</body>
</html>

django_movies/django_movies/templates/index.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}

  <ul>
    {% for movie in object_list %}
      <li>{% movie_format movie %}</li>
    {% endfor %}
  </ul>

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}